@startuml uml

' Compra
class Compra {
    - id: Long
    - data: LocalDate
    - total: Double
}

class ItemCompra {
    - id: Long
    - quantidade: Integer
    - total: Double
}

' Usuario
class Usuario {
    - id: Long
    - email: String
    - senha: String
}

class PessoaFisica {
    - id: Long
    - cpf: String
    - dataNascimento: LocalDate
    - nome: String
}

enum Sexo {
    + MASCULINO
    + FEMININO
}

enum Perfil {
    + USER
    + ADMIN 💪😎👍
}

class Endereco {
    - id: Long
    - cep: String
    - logradouro: String
    - bairro: String
    - numero: String
    - complemento: String
    - cidade: String
    - estado: String
}

class Telefone {
    - id: Long
    - ddd: String
    - numero: String
}

' Notebook

class Notebook {
    - id: Long
    - descricao: String
    - preco: Double
    - modelo: String
    - isGamer: Boolean 
} 

class Fornecedor {
    - id: Long
    - nome: String
    - email: String
    - telefone: String
    - cnpj: String
}

class Marca {
    - id: Long
    - nome: String
}

enum TipoPlacaVideo {
    + INTEGRADA
    + DEDICADA
}

enum SistemaOperacional {
    + WINDOWS
    + LINUX
    + MAC_OS
}

class Recursos {
    - id: Long
    - descricao: String
}

' Linha e Série

class Linha {
    - id: Long
    - linha: String
}

class Serie {
    - id: Long
    - serie: String
}

' Placa de Video    
class PlacaVideo {
    - id: Long
    - modelo: String
    - memoriaVideo: String
}

enum FabricantePlacaVideo {
    + NVIDIA
    + AMD
}

class TipoMemoriaPlacaVideo {
    - id: Long
    - descricao: String
}

' Processador
class Processador {
    - id: Long
    - modelo: String
    - geracao: String
    - velocidade: String
    - nucleos: int
    - threads: int
    - memoriaCache: String
}

' Memoria
class Armazenamento {
    - id: Long
    - capacidade: String
}

enum TipoArmazenamento {
    + HD
    + SSD
}

class MemoriaRam {
    - id: Long
    - capacidade: String
    - expansivelAte: String
}


' Tela
class Tela {
    - id: Long
    - tamanho: String
}

'HD, FULL HD, QUAD HD, 4K ULTRA HD
class Resolucao {
    - id: Long
    - resolucao: String
}

'120 Hz
class TaxaAtualizacao {
    - id: Long
    - taxaHz: int
}

' Especificacao
class Especificacao {
    - id: Long
    - altura: String
    - largura: String
    - profundidade: String
    - peso: String
}

' Conexões
class Conexao {
    - id: Long
    - entradasUsb: int
}

'Wifi 6, Bluetooth
class ConexaoSemFio {
    - id: Long
    - conexao: String
}

'AUDIO USB-C ETHERNET_RJ-45USB 3.1 USB 2.0 HDMI LEITOR DE CARTAO
class EntradasSaidas { 
    - id: Long
    - descricao: String
}

Compra "1" *--> "*" ItemCompra
Compra "*" o--> "1" Usuario
Compra "*" o--> "1" Endereco
ItemCompra "*" o--> "1" Notebook

Usuario "1" -up-> "1" PessoaFisica
Usuario "*" *-right-> "1" Endereco
Usuario "1" *-left-> "1" Telefone
Usuario "*" --> "*" Perfil

PessoaFisica "*" -right-> "1" Sexo

Notebook "*" o--> "1" Linha
Notebook "*" o--> "1" Serie
Notebook "*" o--> "1" Marca
Notebook "1" *--> "1" Tela
Notebook "*" o--> "1" Processador
Notebook "*" --> "1" TipoPlacaVideo
Notebook "*" o--> "1" PlacaVideo
Notebook "*" o--> "*" Armazenamento
Notebook *--> "1" MemoriaRam
Notebook "1" *--> "*" Conexao
Notebook "1" *--> "1" Especificacao
Notebook "*" --> "1" SistemaOperacional
Notebook "*" o--> "*" Recursos
Notebook "*" o--> "1" Fornecedor

PlacaVideo "*"--> "1" FabricantePlacaVideo
PlacaVideo "*" --> "1" TipoMemoriaPlacaVideo

Tela "*" o--> "1" Resolucao
Tela "*" o--> "1" TaxaAtualizacao

Armazenamento "*" --> "1" TipoArmazenamento

Conexao "*" o--> "*" ConexaoSemFio
Conexao "*" o--> "*" EntradasSaidas

Fornecedor "1" *-left-> "1" Telefone

@enduml