quarkus.datasource.db-kind = postgresql 
quarkus.datasource.username = notelabadmin
quarkus.datasource.password = 151100
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/notelabbd

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql = true
